use_default_settings: true

general:
  debug: false
  instance_name: "__SEARXNG_INSTANCE_NAME__"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "__SEARXNG_SECRET_KEY__"
  limiter: false
  image_proxy: false
  method: "POST"

ui:
  static_use_hash: true

outgoing:
  request_timeout: 5.0
  max_request_timeout: 15.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true
